#ifndef GISTPLUGIN_GLOBAL_H
#define GISTPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(GISTPLUGIN_LIBRARY)
#  define GISTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GISTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GISTPLUGIN_GLOBAL_H

